apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: etait-ici 
  name: etait-ici 
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: etait-ici 
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: etait-ici 
    spec:
      containers:
        - image: cdssnc/etait-ici
          imagePullPolicy: Always
          name: etait-ici 
          env:
            - name: PORT
              value: '3000'
          resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
