resources:
  - api-deployment.yaml
  - api-service.yaml
  - traefik-ingress-controller-cluster-role-binding.yaml
  - traefik-ingress-controller-cluster-role.yaml
  - traefik-ingress-controller-deployment.yaml
  - traefik-ingress-controller-service-account.yaml
  - traefik-ingress.yaml

